remote_theme: marella/jekyll-theme-documentation

permalink: pretty
nav:
  - Home:
      - Home: ''
  - Introduction and Prerequisites:
      - Introduction: intro/intro
  - Hello, Tapis:
      - Hello, Tapis: hello/hello
  - Tapis Systems:
      - Intro to Systems: systems/intro
      - Creating a VM System: systems/vm
      - Creating an HPC System: systems/hpc
      - Creaging an S3 Bucket System: systems/s3
  - Tapis Apps:
      - Intro to Apps: apps/intro
  - Tapis Jobs:
      - Intro to Jobs: jobs/intro