remote_theme: marella/jekyll-theme-documentation

permalink: pretty
nav:
  - Home:
      - Home: ''
  - Introduction and Prerequisites:
      - Introduction: intro/intro
  - Hello Tapis:
      - Hello Tapis: hello/hello