remote_theme: marella/jekyll-theme-documentation

permalink: pretty
nav:
  - Home:
      - Home: ''
  - Introduction and Prerequisites:
      - Introduction: intro/intro
  - Registering Systems and Managing Data:
      - Hello, Tapis: hello/hello
      - Intro to Systems: systems/intro
      - Creating an HPC System: systems/hpc
      - Registering System Credentials: systems/credentials
      - Managing Data on a System: files/data
  - Creating Applications and Running Jobs:
      - Intro to Apps: apps/intro
      - Creating and Registering a Hello, Tapis app: apps/hello
      - Executing the Hello, Tapis app: jobs/hello
  - All Tapis Systems Tutorials:
      - Intro to Systems: systems/intro
      - Registering a Server: systems/vm
      - Registering an HPC System: systems/hpc
      - Registering an S3 Bucket System: systems/s3
      - Registering System Credentials: systems/credentials
  - All Tapis Apps Tutorials:
      - Intro to Apps: apps/intro
  - All Tapis Jobs Tutorials:
      - Intro to Jobs: jobs/intro