remote_theme: marella/jekyll-theme-documentation

permalink: pretty
nav:
  - Home:
      - Home: ''
  - Introduction and Prerequisites:
      - Introduction: intro/intro
  - First steps:
      - Hello, Tapis: hello/hello
      - Intro to Systems: systems/intro
      - Creating an HPC System: systems/hpc
      - Managing Data on a System: files/data
      - Registering an App
  - Tapis Systems:
      - Intro to Systems: systems/intro
      - Registering a Server: systems/vm
      - Registering an HPC System: systems/hpc
      - Registering an S3 Bucket System: systems/s3
  - Tapis Apps:
      - Intro to Apps: apps/intro
  - Tapis Jobs:
      - Intro to Jobs: jobs/intro